### ISSUE TITLE
Benchmark and consider moving more annealer iteration into fathom-trainees

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#1]
Subjectively, it seems like training ran faster when the ruleset was hard-coded into FathomFox, rather than each annealer iteration being kicked off by a message send to a separate webext. Benchmark this. If it's true, do larger chunks of work in fathom-trainees to avoid messaging overhead. One strategy could be to factor the async annealer out into Fathom itself and call out to it from fathom-trainees (to avoid fathom-trainees itself become too large and a maintenance burden for forkers).

**Comment by globau** [comment]
the overhead of these intra-extension messages appears to be in the order of 9%; as per our chat what we'd gain here isn't worth the complexity of moving logic into a training webext.

**Comment by erikrose** [comment]
To complete the account of what Glob found, it turns out the updateProgress() function is slow, for another 9%. He'll see what he can wring out of that.
