### ISSUE TITLE
Allow trainee extensions to run arbitrary callables to determine success

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#18]
Refactor the FathomFox trainer and fathom-trainees so we can explore alternate success predicates in the trainee extensions. For example, rather than being hard-coded to run a ruleset and report whether the returned item is the one labeled, the trainee should be able to supply arbitrary code to compare the returned node's CSS background image with a set of URLs stored somewhere.

As well as serving short-term goals, this will let us experiment with alternate success functions (#12) without having to be architecture astronauts.

**Comment by globau** [comment]
https://github.com/mozilla/fathom-trainees/pull/2

**Comment by erikrose** [comment]
See https://github.com/mozilla/fathom-trainees/commit/6a0ca6b59ff70fcf05eb13906829b62856133a10#diff-ee8d77ac92539c336ddc612d65742c9aR27 for the docs.
