### ISSUE TITLE
http://www.4j.com/Death-Row page is not downloaded if it's a part of a batch in Corpus Collector 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/fathom-fox#21]
**[Affected versions]:**
- Firefox Nightly 67.0a1 
- FathomFox 2.3

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Latest FathomFox add-on is installed
- Have a batch of links:
http://www.agame.com/game/paws-to-beauty-christmasedition
http://www.4j.com/Death-Row
http://8iz.com/game/build-a-bridge

**[Steps to reproduce]:**
1. Reach Corpus Collector page in Firefox.
2. Copy-paste the batch of links in the Corpus Collector.
3. Click on "Download" button,
4. Observe the downloaded pages.

**[Expected results]:**
- All pages are downloaded.

**[Actual results]:**
- http://www.4j.com/Death-Row page is skipped and only 2 pages are downloaded.

**[Notes]:**
- If http://www.4j.com/Death-Row is not part of an batch (downloaded alone), the download is made successfully.
- When opening http://www.4j.com/Death-Row in a new tab, a popup is displayed on top of the page. Maybe this has something to do with the issue.
- Screenshot of the issue attached

![loading](https://user-images.githubusercontent.com/9248513/52048203-7a8bb400-2553-11e9-8537-3f4ddeab782b.png)

**Comment by Softvision-VladBacia** [comment]
Found other pages for which the issue is happening (if the webpages are part of a batch):
- http://www.funnygames.biz/game/prison_break_out.html
- http://www.hoodamath.com/games/redremoverplayerpack.html

**Comment by erikrose** [comment]
I recently fixed a series of bugs in the Corpus Collector but have yet to publish the fixes. Trying it on my latest code, your above batch of 3 works—or at least fails differently: the first fails with "unexpected removal of DOM element". The second two work.

I expect to release the fixes as FathomFox 2.3.2 or 2.4.

Thanks for the good reports, Vlad!

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Nightly Build ID: 20190331215222 with FathomFox 3.0 and it is no longer reproducible. Thus, marking this as Verified - Fixed.
