### ISSUE TITLE
Duplicates are created when using multiple times the same Corpus Collector tab

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/fathom-fox#22]
**[Affected versions]:**

- Firefox Nightly 67.0a1 
- FathomFox 2.3

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Latest FathomFox add-on is installed
- Have a batch of links:
http://www.agame.com/game/paws-to-beauty-christmasedition
http://www.4j.com/Death-Row
http://8iz.com/game/build-a-bridge
http://www.addictinggames.com/puzzle-games/creepy-halloween-difference-game.jsp
https://ovh-cdn.amt-games.com/web/custom/bfg.html
https://bigdino.com/play/1100/Rats-Invasion
https://www.bubblebox.com/play/1720/ducklife.htm
https://www.newworldempires.com/index.php
http://www.cargames.com/Sniper-Assassin-4
https://www.bgames.com/sport-games/darts--beer/

**[Steps to reproduce]:**

1. Reach Corpus Collector page in Firefox.
2. Copy-paste the batch of links in the Corpus Collector.
3. Click on "Download" button,
4. Observe the downloaded pages from the download folder.
5. After all downloads are done, delete the links from Corpus Collector page.
6. Paste other links and click on Download button.

**[Expected results]:**
- All pages are downloaded and no dupes are created

**[Actual results]:**
- Duplicates are created after multiple uses of the same Corpus Collector tab

**[Notes]:**
- This scenario can be observed using the same links but before every use, the downloaded HTML files must be deleted from the download location. Just repeat steps 5 and 6.
- Screenshot of the issue attached

![duplicate](https://user-images.githubusercontent.com/9248513/52053825-212b8100-2563-11e9-96ee-81e01062705c.png)

Video of the issue can be found **[HERE](https://drive.google.com/open?id=1MDG4s0f9rN_zouoZhJGyseFnCrd2ow54)**.

**Comment by Softvision-VladBacia** [comment]
I've also encounter this issue when downloading multiples HTML files (78 links) with Corpus Collector.
![dupes](https://user-images.githubusercontent.com/9248513/52577359-9b44eb00-2e2a-11e9-9e59-c1316f489641.png)

**Comment by erikrose** [comment]
I'll publish a release tomorrow, and you can let me know if you still have problems. Thanks for the good reports!

**Comment by Softvision-VladBacia** [comment]
The new changes have improved the add-on and it works much better now. In a batch of 100 links, I had only 3 duplicates.

**Comment by erikrose** [comment]
Oh, good. I'm still having some problems as well. Let me see if I can squash them.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Nightly Build ID: 20190331215222 with FathomFox 3.0 and it is no longer reproducible. Thus, marking this as Verified - Fixed.
