### ISSUE TITLE
Improve freeze speed

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#38]
It takes 3 minutes and 12 seconds on my 2017 MacBook Pro to serialize https://stuffdutchpeoplelike.com/product/stroopwafel-teething-toy-bijtring/ (from the devtools panel, though that shouldn't matter). During the process, Firefox maxes out 1 entire CPU core and also sucks up an additional 5GB RAM. This makes corpus collection more of a drag than it needs to be. Profile and see what's taking so long. Reducing RAM use would be a bonus.

**Comment by danielhertenstein** [comment]
A profile of the above linked page is here: https://perfht.ml/2JBhYWC

Some observations from the profile:
- 80.24% of the time is spent in freezeDry's `setTargetLink`
- ~70% of the time is spent in an `isEqual` method which is primarily comparing strings
- These operations take place when inlining subresources

**Comment by danielhertenstein** [comment]
Interestingly, upon updating freezeDry from 0.2.0 to 0.2.4, saving pages no longer works.

This line:
https://github.com/mozilla/fathom-fox/blob/9b912df2dfe2ecea42612e4458c54bab538cbee7/addon/background.js#L30 

is giving the error: `Error: Could not establish connection. Receiving end does not exist.`

**Comment by erikrose** [comment]
This is one of the classic webext IPC errors. Sometimes they're intermittent: that same error is why the Retry checkbox exists in the Vectorizer. (In that case, the receiving end is a singleton in background.js and should exist from the beginning of time.)

**Comment by danielhertenstein** [comment]
I have a PR up for updating freezeDry (#45) and the profile for the same test page is: https://perfht.ml/2JMF5xq. Much much faster and there looks to be a significant portion of time spent waiting (though I don't know enough about how to read these profiles yet to know what the waiting is for).

**Comment by biancadanforth** [comment]
If you're talking about `GetEvent::Wait` and the like, those are raw Gecko/C++ calls and represent browser idle time.

**Comment by danielhertenstein** [comment]
Yup, that is what I'm talking about. I can't tell why the browser is idling that much though. Is freezeDry waiting on the network activity (blue lines) between the two chunks of javascript (yellow)?

**Comment by biancadanforth** [comment]
Hmm... the way I understand browser idle time is that the browser is not busy and is awaiting work. Browser idle time in the profile is its own category (grey) compared to JavaScript (yellow). IIUC, `freeze-dry` is executing only in the extension's content script as JavaScript (Web Content 2/2 process in the profile), so I don't think it is related. I see the idle time in the WebExtensions process, which is a separate process where the background script for the extension runs.

**Comment by erikrose** [comment]
Another way to come at it, which doesn't require understanding the complexities of Firefox's process model and profiler, is to just look at your systemwide CPU graph while freezing. Does it peg a logical core at 100%?

**Comment by erikrose** [comment]
Btw, I suspect your recently landed #45 closes this to my satisfaction. Our pathologically slow Stroopwafel page went from 3:30 to just 0:30 on my machine, so I'm hoping that the average page will now take on the order of a few seconds. We can close this if that ends up being the case, unless you see low-hanging fruit to pick.

**Comment by danielhertenstein** [comment]
I do see 100% core usage when looking at my CPU graph while saving the Stroopwafel page, so I'm going to close this.

**Comment by biancadanforth** [comment]
> I do see 100% core usage when looking at my CPU graph while saving the Stroopwafel page, so I'm going to close this.

Late to the game here, but why is 100% core usage considered an improvement?

**Comment by danielhertenstein** [comment]
It was to make sure the waiting I had mentioned in the profile isn't actually a problem.
