### ISSUE TITLE
UI tweaks to the devtools pane

### ISSUE THREAD

**Issue by globau** [mozilla/fathom-fox#4]
- add a notification immediately after hitting save to indicate that it's working, something like "Preparing download, please wait..." should suffice
- hitting return while the labelling field has focus should submit
- there should be some way to view existing labels; even if it's a simple console query, or a line you can copy+paste into the console to generate the list

**Comment by erikrose** [comment]
There's this lovely little spinner GIF I used on DXR: https://github.com/mozilla/dxr/blob/master/dxr/static_unhashed/images/spinner-large.gif. All you have to do is show and hide it (and maybe disable the Save button while it chews).

**Comment by globau** [comment]
i was thinking along the lines of a pure css spinner - https://codepen.io/anon/pen/xJQjEg :)

**Comment by erikrose** [comment]
wfm!

**Comment by globau** [comment]
this is mostly done:

![image](https://user-images.githubusercontent.com/872825/44385880-54e59200-a553-11e8-943b-f0a4c783d7b8.png)

the top row is the currently selected/inspected element.  the ⦸ button that row clears the label text field.

below are all the labelled elements; the ✖︎ removes the label from that element, resulting in it being removed from the list.

i removed the save button completely; instead updates are made to the element when the input field is changed.

clicking on the css path in the left column switches to the inspector tab with that element selected.  it's also used as a distinguishing factor between the currently selected element and the remainder of the table.

finally clicking on the save/freeze button disables that button and shows a spinner, which is hidden when the save file dialog is closed.

![image](https://user-images.githubusercontent.com/872825/44385889-5e6efa00-a553-11e8-87c4-e3b8131aae56.png)

**Comment by erikrose** [comment]
I love it! Great job! The only tweak I'd make is to lose the circle-cross button, since I spent some time puzzling over how it's different from X before I read your description and there are plenty of other ways to clear the field.

**Comment by erikrose** [comment]
Especial props for live-updating the DOM. Makes for fewer buttons. :-)
