### ISSUE TITLE
Remove Train button

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#43]
The Evaluate button is still useful as a debugging tool until #39 is implemented, but the "Train on the tabs in this window" and Pause buttons are attractive nuisances that don't even train Fathom 3 rulesets properly (for instance, they aim for per-page accuracy, meaning they won't work for applications that find multiple occurrences of the same type of entity). Remove them and any code that goes dead as a result (all the training code in FathomFox, for starters).

**Comment by biancadanforth** [comment]
@erikrose What does the Evaluate button do exactly?

**Comment by erikrose** [comment]
It runs the ruleset with the coded-in coefficients, without training or otherwise modifying them. This has the useful result of showing you which pages it failed on and, further, lets you click failed, red cells to see what element, if any, Fathom spuriously picked.
