### ISSUE TITLE
Embed URL in frozen pages

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#44]
We're typically interested in preserving the URLs of captured pages, for instance to ensure we don't overrepresent one site. We've done this manually, but it takes time, and sometimes we forget or mess it up or lose the list. Let's embed the URL in the page automatically, in a place invisible to the viewer and unlikely to be mistaken for original page content. Data attribute on the root tag? `fathom-url`? I think there was also a convention freeze-dry used to store the original img src URL. We could follow that instead.

**Comment by danielhertenstein** [comment]
This is actually solved by #45.
