### ISSUE TITLE
Stop Vectorizer when an error occurs

### ISSUE THREAD

**Issue by danielhertenstein** [mozilla/fathom-fox#52]
If an error occurs in the process of vectorizing a page, the Vectorizer will happily move on to the next page, fail, move on to the next page, fail, and continue like this for all of the pages. Instead we should stop the Vectorizer so the user is more obviously alerted that something bad has happened.

**Comment by biancadanforth** [comment]
Note: This is a follow-up from PR #46 .

**Comment by danielhertenstein** [comment]
Closed by #55 with the caveat that there are known errors that we do not handle well yet and therefore do not stop the vectorizer upon occurring. #61, #62, and mozilla/fathom#163 will address those known errors, but I wouldn't be surprised if there are more. There are always more. Regardless, original intent of this issue was addressed by #55, so I'm closing this issue.
