### ISSUE TITLE
Make the HTTPS certificate warning less of a stumbling block

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom-fox#56]
In https://github.com/mozilla/fathom/pull/117, @danielhertenstein added a new `fathom-serve` tool that spins up an HTTPS server to serve local frozen sample pages. This is used for FathomFox's Vectorizer among other things.
For Firefox to load a page from an HTTPS web server, the server has to have a certificate that is trusted. We are currently using a self-signed certificate and asking the developer to trust us by clicking through a warning in Firefox the first time a page is served during that session. Can we add our server certificate to the list of trusted certificates in the temporary profile used by FathomFox?

Here's the warning displayed currently:
![Screen Shot 2019-10-04 at 1 08 13 PM](https://user-images.githubusercontent.com/17437436/66240241-f3c64280-e6b0-11e9-8cba-afc0aadc6f4c.png)

I talked to Dana Keeler, a security engineer who works on security certificates, and here's what she suggested:
> the easiest way would probably be to use certutil to add the certificate to the temporary profile's cert9.db as a trust anchor

Here's a further breakdown of the steps:
1. `brew install nss`
2. Create a Firefox profile directory
3. Use NSS' `certutil` CLI to trust the server certificate in the newly created profile
4. Pass `web-ext run` the path to that profile directory

As part of this issue, we should also include a brief explanation in the docs about why we have to use HTTPS in the first place[1], as it is a lot more effort.

----

[1]: Why HTTPS rather than HTTP?
Using the `freeze-dry` library to freeze an HTML page inlines all of its resources, making the HTML file very large--too large to store such files on GitHub.
This is a problem, because we want to keep these files associated with their Fathom rulesets. After some thinking, we converged on Git LFS as a solution, which lets us store large files elsewhere and keep references to those files in a GitHub repo.
This required moving the resources out of the HTML document, keeping the HTML document in the GitHub repo, and its resources in Git LFS (@danielhertenstein created the [`fathom-extract` CLI](https://github.com/mozilla/fathom/pull/109) to do this).
By moving resources outside the page, directories or otherwise, we encountered [CORS restrictions related to how `file:///` URLs are handled](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp#Local_File_Security_in_Firefox_68). Basically, when a resource is requested from another file, that's treated as a CORS request, and CORS requests may only use the HTTPS scheme.

**Comment by erikrose** [comment]
Since we chatted on IRC a few hours ago, I recalled that there are several CORS-controlling about:config flags (search for "cors" and "cross"). It's pretty heavy to start [automatically] installing brew packages. Maybe we can just twiddle those flags more easily?

**Comment by biancadanforth** [comment]
You know, I was thinking more about it Friday, and I am wondering... @danielhertenstein , Why do we need an HTTPS server? If we have a local HTTP server, the browser should treat that as `http://` protocol, not `file:///` protocol.

I just tried a regular HTTP server via `python3 -m http.server 8000 --bind 127.0.0.1` for the Vectorizer step at least, and the pages loaded normally, and it produced the same `vectors.json` file as with the HTTPS server via `fathom-serve`. Maybe I am missing something?

**Comment by danielhertenstein** [comment]
@biancadanforth, I think you are right. I am able to create vectors for the shopping set with a regular HTTP server. The only thing I can think of is that I was loading pages through my file explorer (using `file:///`) when I was testing the extractor's correctness, and so was unnecessarily causing the CORS restrictions. That would be frustrating and embarrassing for me, though it would be good news for Fathom.

**Comment by erikrose** [comment]
I second. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp says CORS requests must be HTTPS, but we're not dealing with CORS requests as long as we avoid file URLs: the host and port are the same for all requests.
