### ISSUE TITLE
Merge this repo into fathom

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#66]
The main motivations are…
* We could use atomicity between the two. For example, a lot of the code FathomFox runs, indirectly, lives in Fathom's trainees.js module. Adding a FathomFox feature often means changing FathomFox and that.
* We already have Fathom's Python-based CLI tools in the Fathom repo, and releasing 2 things from 1 repo has gone just fine for several iterations.

Bonus: It'll make testing fathom-vectorize easier, which otherwise has to explicitly check out a bunch of repos, just hoping that all the master branches are compatible.

**Comment by HackyRoot** [comment]
I'd like to pick this up!

**Comment by erikrose** [comment]
Sorry, I'm already halfway through it! Besides, it requires GitHub admin permissions. Any other issues interest you?

**Comment by HackyRoot** [comment]
Not an issue @erikrose .
