### ISSUE TITLE
Set a `maxTabs` value that does not trigger the "Unable to connect" error

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom-fox#67]
Parallelizing the Vectorizer (PR #55 ) allowed us to drastically reduce the amount of time it takes to vectorize a large number of samples, however I think we may need to revisit the `maxTabs` value initially set, as empirical evidence suggests that 16 (our current value) tabs causes "Unable to connect" errors, 24 tabs causes even more and 8 tabs cause none.

See [this discussion](https://github.com/mozilla/fathom/pull/164#discussion_r355064636) for more details.

In our case, I think the first bullet point for what is wrong applies: the server is receiving too many requests (or something like that) simultaneously.

![Screen Shot 2019-12-06 at 3 04 21 PM](https://user-images.githubusercontent.com/17437436/70362397-b493a980-1839-11ea-8317-7276a637a761.png)

**Comment by erikrose** [comment]
We're just using the 1-liner HTTP server out of the stdlib, which is single-threaded. I wonder if there's a cheap way to just beef up the server so we can still saturate the CPU, maybe something from https://stackoverflow.com/questions/14088294/multithreaded-web-server-in-python. There's also Flask, which can do multi-thread or multi-process, though I wouldn't want to do it if it involved more than 20 lines of code.
